# fly.toml app configuration file generated for tu-app on 2024-01-15T10:00:00Z
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "tu-app-backend"
primary_region = "mia"

[build]

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  grace_period = "5s"
  method = "GET"
  path = "/"
  protocol = "http"
  timeout = "10s"
  tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[deploy]
  release_command = "npm run migrate && npm run create-machines"

[[statics]]
  guest_path = "/app/uploads"
  url_prefix = "/uploads"