# fly.toml app configuration file generated for backend-xzscwq on 2025-08-11T23:02:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-xzscwq'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
